name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
       inputs:
         run_job:
            description: 'Run specific job'
            required: false
            type: boolean
            
         custom_message:
            type: string
            required: true
            description: 'enter a custom message'    
             
                 

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  job2:
      runs-on: ubuntu-lates
      steps:
       - name: Printing custom message
         run: echo {{inputs.custom_message}}
